### ISSUE TITLE
CPU Question

### ISSUE THREAD

**Issue by diego3** [tizian/Cendric2#1]
Hi,

Your game is cool, and would like to say it is a great work, just keep going on :)

I have one question:  I download the binaries and i tried your game for a while, so i noticed that my cpu was about 50%, it is normal ?  Are you using opengl rendering capabilities in your engine ? 

I am asking it couse when i run other games they dont consume so much cpu, but it is just a feedback :)

My PC is a Dual Core processor running under windows 7 and i have a GPU with 1GB RAM!

**Comment by Ironbell** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/9303244/19734353/8bad6ba8-9ba7-11e6-9b24-a9810dadd1d9.png)

Good point. I attached a screenshot of the game running in debug mode (which is usually even more costly) on Windows 10, 4 cores. It takes only 6% of my CPU, but it's  consumption is only gated  through the VSync (which is set to 60 frames per second on my GPU). 

Do you have VSync turned on? What version of the game did you test? Could you turn on the debug mode (press F11 ingame) and tell me on how  many FPS the game runs? We could add an option to limit the game's update rate (to, for example, only 30 iterations per second)

**Comment by diego3** [comment]
Cendric_v0.3.0b_win64   release, 
Now i'm not in my house, so later i'll check vSync and test debug mode!

Thanks for you fast response rsrs,  (Ah, I noticed you was playing Word of Warcraf, the Movie is very amazing, althought i haven't played the game yet! :)

**Comment by Ironbell** [comment]
![screen3](https://cloud.githubusercontent.com/assets/9303244/19875552/f1bb7da2-9fcd-11e6-81bd-59111d62fb8b.png)

As the CPU consumption can really be an issue on computers with a weaker CPU, we've added an option to control the frame and update rate. It can be accessed in the options screen where users can choose whether they want to limit the frame rate (30-100 FPS). Internal, it uses the method SFML provides which then uses Thread.sleep(). This can cause small lags, especially when set to the bare minimum (30 FPS) and without using VSync. But that's for the user to choose - we don't recommend limiting the frame rate and it's off per default. Physical simulations like the water and the objects influenced by gravity still work in the FPS range that is provided. 

It would be nice if you could try out the new feature and tell us how much it affects the gameplay and the CPU consumption on your PC. If you don't want to compile yourself from the master branch, I can do that for you.
