### ISSUE TITLE
softlock?

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#101]
During the "race" level with Logan III with the automatically moving cam it is possible to get stuck. The only way out was to leave the level. Maybe it would be better to just die if Cendric gets stuck between the border of the screen and a wall.

**Comment by eXpl0it3r** [comment]
Or not get stuck between the border of the screen and a wall. 😉

**Comment by Kylaine** [comment]
That's the goal of course. But if it does happen, and it will probably happen again, it feels irritating.

**Comment by Ironbell** [comment]
Can you show me the exact location where you get stuck? Cendric dies when he gets squished from the autoscroller level.
