### ISSUE TITLE
Ingrids Eintopf Bug Mac

### ISSUE THREAD

**Issue by LordHeinrich** [tizian/Cendric2#103]
Drank Ingrids eintopf in the Howling cave, my health is decreasing into the negative spectrum but I am not dying.

**Comment by Ironbell** [comment]
Negative Health is fixed by now (see #66) and also in the next build. The Eintopf bug is new though.

**Comment by Ironbell** [comment]
Can't reproduce on windows. We got no uninitialized variables here. @tizian ?

**Comment by Ironbell** [comment]
Is not reproducible.  If it occurs again in a newer build, please reopen.
