### ISSUE TITLE
Yasha Temple randomly dying (mac)

### ISSUE THREAD

**Issue by LordHeinrich** [tizian/Cendric2#107]
Not sure if this is a game mechanic that I missed with the temple but so far I usually end up dying at random spots in the temple. Nothing with damage or so, one moment I'm on full health the next I'm dead. Some the spots appear to have some sort of a pattern, however it doesn't always work the same way.

**Comment by Ironbell** [comment]
The swinging tiles maybe? Or spikes? They're all one hit. If you can, send me a screenshot of you dying at an unfair spot.

**Comment by LordHeinrich** [comment]
In an attempt to see if I missed a dialog I reloaded a save and was promtly stuck back in Gandria. Ill replay until the temple then I will send you some screenshots,
although I‘m not sure I‘ll manage before week 2 of the Beta. Im 100% sure spikes didnt kill me, and if by swinging tiles you mean the moving spike platform then thats a no as well. One of the spots where I died a lot was on the right side of the entryway on the edge of the lava lake.

**Comment by Ironbell** [comment]
Those things would kill you as well if they hit.

![image](https://user-images.githubusercontent.com/9303244/32908397-b846f440-cb03-11e7-92c2-f89ca4bb41e0.png)

I updated the lava range to eliminate possible rounding  errors. Please reopen if problem persists.

**Comment by LordHeinrich** [comment]
Then that must be a graphic bug, because I cant see them.

<img width="1277" alt="screen shot 2017-11-16 at 20 19 52" src="https://user-images.githubusercontent.com/33522113/32911238-dc18f050-cb0b-11e7-8bd9-55f897d36683.png">
<img width="1280" alt="screen shot 2017-11-16 at 20 19 43" src="https://user-images.githubusercontent.com/33522113/32911239-ddb85acc-cb0b-11e7-9fb1-07f148eec652.png">
<img width="1276" alt="screen shot 2017-11-16 at 20 20 00" src="https://user-images.githubusercontent.com/33522113/32911240-df1ab126-cb0b-11e7-88df-2145325819a1.png">

**Comment by Ironbell** [comment]
OH DARN
