### ISSUE TITLE
Maybe Logic Issue

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#109]
When joining another guild than the clerics. Lloyd knows instantly about your choice. I don't know why but he always know, even if I wear normal cloth.
Possible resolutions would be that the magic aura of cendric changes if you join a guild or you get marked with the emblem on your hand.

**Comment by Ironbell** [comment]
It's handled the same way in the Gothic & Risen games (which heavily influenced Cendric). People always know which guild you're in. But as we have magical auras in this game, it might be a possible explanation. I'll think about it :)

**Comment by Ironbell** [comment]
Nop.
