### ISSUE TITLE
Floating Leafes

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#112]
I found some more leafes floating around, a little bit annoying. :D

![freeleafes6](https://user-images.githubusercontent.com/12735077/32965487-e8c0b614-cbd6-11e7-925a-20991a149e78.PNG)
![freeleafes5](https://user-images.githubusercontent.com/12735077/32965489-e8dd3a50-cbd6-11e7-893c-92a29b48a4f3.PNG)
![freeleafes4](https://user-images.githubusercontent.com/12735077/32965490-e8f4f0be-cbd6-11e7-871e-a78c36b9eedc.PNG)
![freeleafes3](https://user-images.githubusercontent.com/12735077/32965491-e90cf510-cbd6-11e7-8632-27c1787d5832.PNG)
![freeleafes2](https://user-images.githubusercontent.com/12735077/32965492-e92d463a-cbd6-11e7-90db-94892487b667.PNG)
![freeleafes](https://user-images.githubusercontent.com/12735077/32965493-e94f3768-cbd6-11e7-8305-843f90e4cc79.PNG)
![freeleafes9](https://user-images.githubusercontent.com/12735077/32965494-e9684e88-cbd6-11e7-86ca-84bfc175e408.PNG)
![freeleafes8](https://user-images.githubusercontent.com/12735077/32965495-e9864fdc-cbd6-11e7-989b-1e25b5a310de.PNG)
![freeleafes7](https://user-images.githubusercontent.com/12735077/32965496-e9aa501c-cbd6-11e7-9cf2-2ed42bb3f369.PNG)

**Comment by Ironbell** [comment]
They are ok. The ones you reported earlier was really floating, but those are just decoration
