### ISSUE TITLE
Can stand on that 1 pixel

### ISSUE THREAD

**Issue by RaymonWe** [tizian/Cendric2#114]
You can stand on the block below movable blocks(I don't know how better describe it):
![2017-11-20 22-50-00](https://user-images.githubusercontent.com/33033939/33043781-db354dd0-ce46-11e7-9685-13dd638838b8.png)

**Comment by Ironbell** [comment]
That's ok. They are 48px wide. It seems strange but it's actually ok. It doesn't break any puzzles yes?
