### ISSUE TITLE
Suggestion: switch "tönt" with "klingt" in German

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#115]
In some dialogues it says phrases like "das tönt ja grossartig" and I think saying "Es tönt gut" is something that is only said in Switzerland and Germans rather say "Es klingt gut", so maybe change the word, because it might sound a bit weird for Germans.

**Comment by Ironbell** [comment]
I will do so and search once through the entire database. Let's see how many I'll find.

**Comment by Ironbell** [comment]
+3
