### ISSUE TITLE
Spelling errors German, Chapter 1

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#116]
erstes Treffen Wirt, frage nach dem Schnaps: "[...]und ihnen ihre Schafe stielt." -> stiehlt mit h
Thea: "ich bin eine Magd auf Ivo's Bauernhof." -> Ivos, im Deutschen ohne Apostroph :)
Dialog mit Ivo: "Ich habe ghört,..." -> gehört
Ivo: "So lange sie uns in Frieden lassen,..." - "solange" als ein Wort
Inina: 
- "...der dazu dient, dich aufzspüren" -> aufzuspüren
- "Der Paladin den wir in die Höhle [...]" -> Paladin, den
- nach Besiegen des Bosses: "Ich bin höchst beeindruckt bei deinen Fähigkeiten" -> "von deinen Fähigkeiten"
- "Emfehlungsschreiben" -> "Empfehlungsschreiben"

Dialog mit Stadtwache: "aber er ist immernoch sich selbst" -> "immer noch", "[...] er selbst" und Komma vor "aber"

**Comment by Ironbell** [comment]
+11. Genitiv Apostrophe wird man noch einige finden, ich hatte diese Regel falsch im Kopf.
