### ISSUE TITLE
Spelling Errors Chapter 2 German (first part)

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#117]
This is only the first part of errors in this chapter, I guess there will be more.

Steven: "Aber du kannst auch nicht mit ihr sprechen bis [...]" - "ihm" statt "ihr" gemeint? Komma vor "bis"

Harek: 
- "[...], falls du mir die Materialen besorgen kannst." - Materialien
- "hast du spezielle Materialen und etwas Eisenerz gefunden?" - Materialien
Im Dialog mit Vincent: "Gib mir diesen Schlüssel, ich machs." - mach's
Vincent: "Oh, und sie ist wahrscheinlich von Beobachter-Zauber beschützt." - entweder noch ein "einem" vor Beobachter-Zauber, oder "von Beobachter-Zaubern"

In der Taverne in Gandria, Dialog mit Helena: "Okay, sag mir was du über mich weisst." - Komma vor was
Helena: 
- "Aber ich habe die Sachen die ich nicht verkaufen konnte hier unter der Theke gelagert" - "Sachen, die" und "konnte, hier"
- "Oh, an die erinner ich mich nich mehr." - nicht

Jeremy: "Oh, du meinst diesen erbärmlichen Paladin der alles verspielt hat?" - "Paladin, der"

Syrah: 
- "[...]es gibt fast nichts was ich nicht zusammenbrauen könnte." - Komma vor was
- "[...] es gibt auch eine Tür in der Nähe des Hafens die dort runter führt" - Komma vor die

Bürger: "Gandria ist nicht nur die Hauptstadt von Admantris sondern [...]" - Komma vor sondern

Luv: 
- "Hätte er nicht geschlafen als unser Kapitän die Matrosen [...]" - Komma vor als
- "Wir wissen wo unser Kapitän hinwollte" - Komma vor wo

Jonathan: 
- "Das ganze Gedächnis zu verlieren ist ziemlich ungewöhnlich" - Gedächtnis
- "wir können das gesammte Spektrum der Magie verstehen" - gesamt
- "Ich wusste, dass mir Cyrus einer seiner Studenten [...]" - einen seiner Studenten
- "Ausserdem ist jemand, der sein Gedächnis verloren hat,[...]" - Gedächtnis 
- (nach Erlernen der Feuermagie) "Es ist einfach so dass ich in letzter Zeit[...] Ich denke nicht dass du eine Ausnahme warst" - zweimal Komma vor dass
- "Rausgehen scheint keine gute Idee für mich zu sein bis diese Stadt wieder normal ist" - Komma vor bis
- "[...] von denen sich jede auf einen anderen Bereich der Magie spezilisiert" - spezialisiert
- (auf Frage nach Nekromanten) "Sie durfen sich nicht öffentlich zeigen weil ihre Magie[...] Wenn ich dich wäre, [...]" Komma vor weil, "Wenn ich du wäre"
- (Frage nach Dämmerungsmagie) "Magier die sich mit Dämmerungsmagie beschäftigen sind meistens einfach Diebe" - "Magier, die [...] beschäftigen, sind [...]"

**Comment by Ironbell** [comment]
Steven: Nein, er bezieht sich hier auf Inina.
Sonst:  +26p :)
