### ISSUE TITLE
Spelling Errors German, rest of Chapter 2

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#118]
Bei Syrah: 
- "Ich habe was du brauchst." - Komma vor was
- "Ich weiss nicht ob das eine gute Idee ist" - Komma vor ob
Syrah: 
- "Aber jetzt wo ich dir einen Gefallen getan habe, solltest du mir auch einen machen." - Komma zwischen jetzt und wo, tun statt machen
- "Sie wächst nur auf dem Grab von Leuten, die in einem Feuer umgekommen sind." - Besser: "Sie wächst nur auf den Gräbern von Leuten, die [...]"
- "Ich bin mir sicher dass du diese Blume dort finden kannst - Magier, die Magie "missbrauchen" werden [...]" - Komma vor dass und werden

Leeroy: 
- "Ich schaue nur dass niemand zerfleischt wird bevor ich sie erledige." - Komma vor dass und bevor
- "[...] Lloyd hat mich gefeuert weil [...]" - Komma vor weil
- "Tz, das ist weil sie sich verstecken! [...] jemanden wie dich den sie verspeisen können." - Komma vor weil und den

In der Taverne zu den Söldnern: "Helena will, dass ihr ihre Taverne verlässt" - verlasst

In der Kanalisation, Inina: "Ich kenne keinen Zauber der diese Blockade wegdrücken könnte." - Komma vor der

Harek: "[...] zu mir kommen wenn du spezielles Material findest" - Komma vor wenn

**Comment by Ironbell** [comment]
+15
