### ISSUE TITLE
Spelling Errors German, Chapter 3

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#119]
Jonathan: 
- "Ich wusste sie würden es uns nicht einfach machen." - Komma nach wusste
- "Ich habe gehört dass der Leuchtturmwärter [...]" - Komma vor dass
- "Ich bin mir ziemlich sicher dass [...]" - Komma vor dass
- "Und mit all den Leuten die verschwinden [...]" - Komma vor die
- "Der einzige Magier in Gandria der sich mit Erdmagie auskennt ist ein Typ names Koray" - "in Gandria, der", "auskennt, ist", namens
- (Cendric:) "Was sollten wir jetzt ohne die Karte tun?" - Besser: sollen
- "Ich weiss immer noch wohin sie geführt hat." - Komma vor wohin
- "Und der Schlüssel, um dort hinzukommen war Elementarmagie" - Komma vor war
- "Finde das Geheimnis bevor diese [...]" - Komma vor bevor

Mona: "Dann musst du warten bis sie wieder gehen." - Komma vor bis

Jack: 
- "[...] wollte sich nicht zeigen als [...]" - Komma vor als
- "zugeschlossen damit niemand gefressen wird" - Komma vor damit
- "[...] es wäre toll wenn du mir meine Pfanne [...]" - Komma vor wenn
- "Hier, nimm das Gold dass ich hier ausgeben wollte" - das nur mit einem s

Adelya: "Siehst du nicht dass ich beschäftigt bin?" - Komma vor dass

Lloyd: 
- "Trotzdem braucht Inina immernoch deine Hilfe was das Erkunden [...]" - Komma vor was
- "Ich will dass du ohne weitere Abstecher [...]" - Komma vor dass
- (nach Kampf in der Kanalisation) "Doch, viel wichtiger ist, dass [...]" - Nach Doch kein Komma
- "Ich habe dir doch gesagt du sollst sie befragen [...]" - Komma nach gesagt
- "Aber das war das letzte mal, [...]" - Mal gross geschrieben
- "Der Author des Briefs [...]" - Autor
- "Ich glaube er meint [...]" - Komma nach glaube
- "Es gibt einen verlassenen Temel im Hochland" - Tempel
- "[...] wirst du an einen dunkeln Abgrund kommen" - dunklen
- "[...] in einem solchen dunkeln Abgrund [...]" - dunklen

Helena: "[...] dass du sie tötest aber es ist auch ein Weg [...]" - Komma vor aber

Dialog mit Jeremy: "Wir vermuten ihr habt etwas mit ihrer Entführung zu tun" - Komma nach vermuten

**Comment by Ironbell** [comment]
That's some impressive proofreading. I must admit though that I never checked the German version and the ,,,,,,,,,,,,,,, rules are so different to English 🔤

**Comment by Ironbell** [comment]
+28. I couldn't find the "Ich glaube er meint [...]". Neither in Lloyds dialogue nor in any other.
