### ISSUE TITLE
Spelling Errors Chapter 4 German

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#120]
Kapitel 4

Zephyra: 
- "Ich bin Zephyra, Einsiedler und Yasha's Schamanin." - Yashas ohne Apostroph
- "[...]mit rotem, verstrubbelten Haaren" - rotem, verstrubbeltem Haar oder roten, verstrubbelten Haaren

Harek: 
- "[...] Es ist lange her seit ich solche in den Händen gehalten habe" - Komma vor seit
- "langsam frage ich mich wirklich woher du diese Dinge bekommst die du mir bringst" - "wirklich, woher", "bekommst, die"
(Auswahl herstellung): Alastor's Sicheln - ohne Apostroph

Yasha: 
- "Wie ich sehe ist deine Seele rein und deine Magie stark" - Komma nach sehe

Dialog mit Rana: "Sie schläft nicht mehr, ich habe mit mit ihr angefreundet" - mich statt dem ersten mit

Zu verstärkende Waffen bei Jason: Yasha's [...] - 2x ohne Apostroph
Auch im Level, Also Yasha's Heiligtum etc. überall das Apostroph weg
Dialog mit Jason: "Ich habe dieses Schwert im Tempel im Norden gefunden. Weisst du was es ist?" - Komma vor was

Jonathan: "Okay, versuchen wirs" - wir's

**Comment by Ironbell** [comment]
*Einsiedlerin wäre auch noch was.

**Comment by Ironbell** [comment]
+13
