### ISSUE TITLE
Spelling Errors Chapter 5 German

### ISSUE THREAD

**Issue by Arquata** [tizian/Cendric2#121]
König Logan III: "(Logan's Augen leuchten plötzlich auf)" - ohne Apostroph

Velius: "Die drei, ich ich jetzt habe, sind perfekt" - die statt dem ersten ich

Also again in the boss level of Alastor it says Alastor's [...], which should be without apostrophe, I don't know if the mistake also was in other boss levels and I overlooked it.

And I've only looked for errors in the dialogues now, I think there were also some mistakes in quests or notes, I can also look there again.

**Comment by Ironbell** [comment]
+3
