### ISSUE TITLE
THERE IS AN EMPTY CHEST FFS

### ISSUE THREAD

**Issue by minisiite** [tizian/Cendric2#122]
![image](https://user-images.githubusercontent.com/33699285/33448250-cc7ff1fc-d605-11e7-9c15-3f5f840cc828.png)

THERE WAS A CHEST BUT THERE WAS NO LOOT WTF WHAT IS THIS GAME OMG

**Comment by minisiite** [comment]
![image](https://user-images.githubusercontent.com/33699285/33451041-f3eb1b88-d60d-11e7-8637-ca4ead4cc200.png)

 I HAVE SNUCK MAJESTICALLY INTO THE BARRACKS TO FIND ONLY ANOTHER EMPTY CHEST FUELING MY DESPERATION!

**Comment by Ironbell** [comment]
![image](https://user-images.githubusercontent.com/9303244/33452827-c020f7ea-d613-11e7-8cba-b9dee3699667.png)
