### ISSUE TITLE
Climbing ladders easier?

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#133]
I've had a few spots I was pissed on the ladders, since you need to PRESS up when you're close to the ladder, but it's hard to time sometimes.
Could it be ok to just have up pressed, instead of having to press up, to trigger the climbing?

**Comment by Ironbell** [comment]
I need to overthink this whether it destroys something. but it should most likely work

**Comment by Ironbell** [comment]
Sorry, doesn't work. When you climb up a latter and keep the up key pressed you immediately are  on the ladder again. but again, timing shouldn't be such a problem.
