### ISSUE TITLE
The Mercenaries

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#137]
Is Morgiana to powerful?
I know I don't care much for hp and def in my runs, but it's 150 crittical damage! That's a lot!
Nerf?

**Comment by Ironbell** [comment]
You're the second one that asks me for the nerf. I thought she  should deal a lot of damage as you really have time to run out of her range.

**Comment by OGwold** [comment]
Be scared, yes, make yourself a 1 hit kill? no thank you..
Not much, I think removing crit hits could be more than enough. If that's to weak for you, just amp the norm attack instead.

**Comment by Ironbell** [comment]
She's only critting after she's got roy's powers. I reduced her dmg from 100 (with crit 200) to 60 (120). Be sure to wear some armor.
