### ISSUE TITLE
Paladin puzzle saws

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#138]
Is the yellow saws located in the yasha puzzle for paladin shown anywhere else? Because if they are not, it's not a good way to implement the skill, showing you can jump through a saw, when it noes not work on normal saws..
Also, "pick a pit" is not a good way to go. I saw no good indication on where to go, and had to just die to see if it was the right spot. No fun :(

**Comment by Ironbell** [comment]
Map overlay makes it damn easy to find the correct pit. And no, the saw is not but there is a hint.
