### ISSUE TITLE
WP triggers

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#139]
Should you be able to activate WPs before you have the teleporter stone? I feel it's weird that you can activate it before even knowing the teleporting exists, then just warp there when you get the stone. 
Won't complain if you keep it the way it is. Faster ;)

**Comment by Ironbell** [comment]
Activating means you know the spot (let's say a spot with a certain magical power). If you'd have to return to them afterwards it would annoy the players as well.
