### ISSUE TITLE
GUI Scrolling Bug

### ISSUE THREAD

**Issue by Ironbell** [tizian/Cendric2#14]
When scrolling through dialogue options and keeping the up/down arrows pressed, the view is not correctly updated, resulting in selected options that are not currently visible

**Comment by psychonaut04** [comment]
Could block one arrow key if the another one is already pressed?

**Comment by Ironbell** [comment]
up/down means up *or* down. the solution would be to update the view correctly. I'll do that soon. But thankyou :)

**Comment by Ironbell** [comment]
Fixed.
