### ISSUE TITLE
Prisma stone 2

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#141]
I think it's a special item that should be worthy of a pendant instead of a ring. You can have two rings, but only one stone. No big thing, but I just feel like it.
If you don't change it to be a pendant, you might change the overworld light that comes from it to glow around your hand instead of your head. It looks really out of place where it's located now.

**Comment by Ironbell** [comment]
I like the fact that it's a ring, so you can still keep a special pendant and another ring. I'll change the overworld light though, maybe it won't glow there.
