### ISSUE TITLE
Cooldown bug

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#143]
If you use a lasting skill and change anything in the skill section (except removing the skill currently in use) your cool down for all skills are reset.
This is triggered by removing or changing place of both gems and skills

**Comment by Ironbell** [comment]
Oh boy...

**Comment by OGwold** [comment]
And I think I have a new bug for you when you've fixed this one!
i think I know how I'll break the cooldown next. I think this is the th time I'm adding stuff with the cooldown, but I keep finding loop holes!
