### ISSUE TITLE
The lava collider is too wide. 

### ISSUE THREAD

**Issue by Ironbell** [tizian/Cendric2#16]
It burns!!
Take a a look at epsIntersect
Some puzzles are no longer possible

**Comment by eXpl0it3r** [comment]
🚒 🚒 🚒 🚒 🚒

**Comment by Ironbell** [comment]
What.

**Comment by Ironbell** [comment]
Done. >= not >

**Comment by eXpl0it3r** [comment]
It burns, so what do you do when it burns? 🚒
