### ISSUE TITLE
Question: How to add a language

### ISSUE THREAD

**Issue by psychonaut04** [tizian/Cendric2#17]
I can translate the game to brazilian portuguese but i didn't found the correct place for it.

`enum class Language {
	VOID,
	Lang_EN,
	Lang_DE,
	Lang_CH,
	LANG_ES,
        LANG_PT-BR,
	MAX
};`

I could do like this but where i can translate the files?

**Comment by Ironbell** [comment]
check the db/insert_scripts folder. It's highly appreciated that you want to do the translation but it's a lot of work to be done. Also, the additional language has to be on the database as well as an additional column. Check db/init_game_data.sql to add the additional column and run init_gitbash.sh within a shell to update the database.

**Comment by psychonaut04** [comment]
I'll add in a fork little by little, thank you!
