### ISSUE TITLE
Shared Libraries

### ISSUE THREAD

**Issue by Translator5** [tizian/Cendric2#174]
I just faced a problem, running the game on Manjaro (Arch-Based)
Running Cendric asks for a "missing shared library: libsfml-graphics.so.2.4".

May you guys could add this lib in the next release?

**Comment by Ironbell** [comment]
Give me 10min :)

**Comment by Ironbell** [comment]
https://github.com/tizian/Cendric2/releases/download/v0.9.0/Cendric_v0.9.1_ubuntu64.tar.gz

try again?

**Comment by Translator5** [comment]
`[rt5@RT5ML Cendric2]$ ./Cendric`
`./Cendric: symbol lookup error: ./Cendric: undefined symbol: _ZN2sf7Texture12loadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_4RectIiEE`

**Comment by Ironbell** [comment]
this has to do with your version of libudev. I'll try to provide a fix and come back to you.

**Comment by Ironbell** [comment]
Yeah I'm a mess. Here you go :)

https://github.com/tizian/Cendric2/releases/download/v0.9.0/Cendric_v0.9.1_ubuntu64.tar.gz

**Comment by Translator5** [comment]
Works now! Thanks!
