### ISSUE TITLE
Lost steam-sdk

### ISSUE THREAD

**Issue by mikrokode** [tizian/Cendric2#186]
Friend,

Where can I find this header file? this #include "steam-sdk/public/steam/steam_api.h"

**Comment by Ironbell** [comment]
This file is not commited, as it is part of the Steam SDK which is not public. 

Untick the "Cendric Steam" in the CMake file.

![image](https://user-images.githubusercontent.com/9303244/37244442-6259dbee-2489-11e8-970f-2cd9b0a64498.png)

**Comment by mikrokode** [comment]
Firend,

I am new in CMake, can you show me the step in untick CENDRIC_STEAM?

**Comment by mikrokode** [comment]
Friend,

Sorry for my stupid question, the cmake was untick in CENDRIC_STEAM. So, what is the error?

**Comment by Ironbell** [comment]
After you've unticked it, generate the project anew. Do you still have compiler errrors?

**Comment by Ironbell** [comment]
Pull again from master, I commited some more #ifdef.

**Comment by mikrokode** [comment]
Friend,

 I found it from https://github.com/Facepunch/Facepunch.Steamworks/tree/master/Generator/steam_sdk

**Comment by mikrokode** [comment]
Okay okay.

**Comment by mikrokode** [comment]
Friend,

After adding the header, no building error. But this window was displayed. May I know What reason?
![error1](https://user-images.githubusercontent.com/26881536/37245060-97f9219e-24cd-11e8-8449-a4bb0a8b0c44.jpg)

**Comment by Ironbell** [comment]
You should build for x64, not for 32 bit.

**Comment by mikrokode** [comment]
Yup, I built for x64. Then, but all the .dll in the debug folder. But unfortunately, still could not.

**Comment by mikrokode** [comment]
Need I put all the dll into C:\Windows\SysWOW64?

**Comment by Ironbell** [comment]
No, into your Release or Debug folder.
Check out this: http://cendric.ch/code

**Comment by mikrokode** [comment]
I have followed step by step without any mistake. Still could not. I think my laptop graphics card or graphic driver not supported this game.

**Comment by Ironbell** [comment]
Can you show me the error output?

**Comment by mikrokode** [comment]
![image](https://user-images.githubusercontent.com/26881536/37249506-ca371e58-2523-11e8-9dc6-81b9ebd7369e.png)
![image](https://user-images.githubusercontent.com/26881536/37249508-cf6b4c32-2523-11e8-9232-ea7d11a51f8f.png)
![image](https://user-images.githubusercontent.com/26881536/37249511-da68812c-2523-11e8-8574-947986ca008f.png)
Any Idea?

**Comment by Ironbell** [comment]
Also, you built the debug version. Why not set the build configuration to Release? (re-copy the sfml .dlls then, because there are release and debug versions.)

**Comment by mikrokode** [comment]
Friend,

After I copied the db and res folder into the debug folder, it work now. Thank you very much. Your game very nice.

**Comment by Ironbell** [comment]
You're welcome ;)
