### ISSUE TITLE
Add an option to skip "You died" 

### ISSUE THREAD

**Issue by Ironbell** [tizian/Cendric2#190]
Or keep it shorter.

**Comment by Ironbell** [comment]
tor he death reset length should be proportional to the frequency

**Comment by eXpl0it3r** [comment]
You should make it really long so the speed runners will take their time not to die once. 😜

**Comment by Ironbell** [comment]
A speedrunner shouldn't die anyway. hehe.

**Comment by eXpl0it3r** [comment]
They shouldn't but if you make a death take up a lot of time, they'll make sure they don't die. 😉

**Comment by thfrwn** [comment]
... or add permadeath

**Comment by Ironbell** [comment]
"Fair" permadeath without server is nearly impossible to implement. Also, this is a game where you die relatively often ;)
