### ISSUE TITLE
Release version (or 1.0.4) on github?

### ISSUE THREAD

**Issue by thfrwn** [tizian/Cendric2#192]
Hi,

Thanks for publishing the source code of this game on github! I was wondering if the release versions that are mentioned on Steam (latest 1.0.4 at the moment) will be on

https://github.com/tizian/Cendric2/releases ?

At the moment the latest one there is 0.9 pre-release version

**Comment by Ironbell** [comment]
A release version will be uploaded pretty soon (within a week). Until then, you can compile the game yourself or use the (not polished) 0.9.0 version for a demo.

**Comment by thfrwn** [comment]
Awesome, thanks. I'm currently compiling 0.9.0 on OpenBSD just FYI.

**Comment by Ironbell** [comment]
If you're compiling it anyway from source, use the master branch. It's stable.

**Comment by thfrwn** [comment]
Thanks, good to know! I'd like to make this available for the OpenBSD ports and the fetch framework checks size and SHA256 of the distfiles. Just taking a specific commit (like the current master branch) got issues with that github can't/won't guarantee that the files don't change, so this regularly breaks the check of the distfiles if used. This is generally much less of an issue with releases which is why we prefer them.

**Comment by Ironbell** [comment]
I suggest then to wait until the week-end, where we most likely will upload the 1.0.4 releases ;)

**Comment by Ironbell** [comment]
It's released ;)
