### ISSUE TITLE
Consider donate button on homepage

### ISSUE THREAD

**Issue by thfrwn** [tizian/Cendric2#193]
I am probably not the only one who is excited that you chose to publish the source code of your game under MIT/CC-BY-NC-SA. Instead of buying the game on steam that takes its cut of the price anyway, I'd rather donate the amount - and I'm probably not the only open-source enthusiast who feels this way. 

Therefore, I'd encourage you to consider setting up a way to donate e.g. on cendric.ch.

**Comment by Ironbell** [comment]
That's very kind of you, but we don't really take donations. Buying the game on Steam will ensure automatic updates and bugfixes and give you access to achievements. You can also use a GitHub release as a demo version and buy it on Steam if you enjoy it to support us.

**Comment by thfrwn** [comment]
Okay, if that's the best way to support this... I'm just concerned that it sends the wrong message if it shows up in steam sales even though I don't use it in steam. Maybe consider itch.io, humblebundle, or gog.com as DRM-free and Steam client-free alternatives for the future. Best of luck!

**Comment by Ironbell** [comment]
I'll put it on itch.io soon :) I'll write again when it's up.
