### ISSUE TITLE
Custom locations for rw files (saves, config)

### ISSUE THREAD

**Issue by thfrwn** [tizian/Cendric2#195]
Hi,

Can the paths for savegames and configuration files (seems to `*.ini` in this project) be customized? Build-time customization would be enough. I grepped through the source, but couldn't find a good place where this could be set.
Background is that our ports data generally go into a read-only folder (e.g. `/usr/local/share`), and read-write (rw) files go into the home directory or var, mostly `~/.local/share` or `~/.config`.

**Comment by thfrwn** [comment]
to (partly) answer my own question: savegame paths seem to be set here:

`src/GlobalResource.cpp`

`const std::string GlobalResource::SAVEGAME_FOLDER = "saves/";`
and others for `QUICKSAVE_PATH` and `AUTOSAVE_PATH`.

now off to find where `*.ini` paths are stored...

**Comment by thfrwn** [comment]
... and after actually opening the file `GlobalResource.cpp`, I'm greeted by the path to `cendric.ini` in line 4:

`const std::string GlobalResource::CONFIGURATION_PATH = "cendric.ini";`

This may be all that is needed - can you think of any other files that should be modifiable after installation? If not, I think this issue can be closed...

**Comment by Ironbell** [comment]
The path actually depends on whether the preprocessor #define EXTERNAL_DOCUMENTS_FOLDER is set, at least for Windows and MacOS. As you're building it for Linux, those paths are relative to where the executable is. The three modifiable file (types) are savegames ("saves" folder), screenshots ("screenshots" folder) and the "config.ini".

**Comment by Ironbell** [comment]
Feel free to reopen if there are any more questions regarding this.
