### ISSUE TITLE
Spell sounds AND MORE

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#197]
These four are the only spells that loop sounds. I might understand the sound loop on ghost form since it's the only skill that last longer than the sound itself, but not even wind with max duration get a single loop. Ice and Leech on the other hand is a one time use, and should not have it at all.
Remove the looping sound on all spells will only affect Ghost Form, but it won't take anything away from the game.

https://www.youtube.com/watch?v=KaPQbfpvWkA&feature=youtu.be

**Comment by Ironbell** [comment]
This needs an additional change to how spells work:
* leech sound should stop when the spell is disposed but not loop
* iceball should stop when the spell is disposed but not loop

I would keep ghost form and wind looping.

**Comment by OGwold** [comment]
**Sound related**
Khajag uses wind, and in this case it's cool that the wind sound loops, but I'd ask for one of two things. Either make Khajag blow harder so you can't loop, OR, make the sound file have a cleaner (hopefully seamless) cut?
Also, The wind spell that Khajag is doing while you enter the room has no sound.
Ghost Form is now the only duration based skill that has a looping sound. It's not needed, and if it is, the sound does not fit. It's volume changes to much to make a nice loop. To high in the middle and literally no sound on the start and end.


Speaking of Khajag
could you instakill if you're a wolf? It's boring to just wait for a death nibble, especially if you need 4 of them... (done with a potion while being attacked)

**Comment by Ironbell** [comment]
I'd say we also include here the mercenaries theme which is too loud. This issue is now a bit messy but in general it's:
* Check wind spell sound of khajag (still looping)
* Remove loop from ghost form
* Remove loop from iceball spell
* Remove loop from leech spell
* Smoother wind sound loop
* Khajag's hit should instakill after transforming the player

**Comment by OGwold** [comment]
Goodie
