### ISSUE TITLE
map/inventory after bosses

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#199]
After you get the "enemy defeated" screen and everything fade to black. You can cancel this by opening the inventory or map tab. This should not be possible, since this seriously destroy the mood you're setting by fading out and get a victorious screen showing.
I'd change it by simply freezing all interactions/inputs until you're placed wherever you're placed after the fight is done.

This is also possible with the spell-scrolls, but I see no problem in skipping them since it's only informative, and does not give you a moody fade out.

**Comment by Ironbell** [comment]
Solution: Adding forced ScreenOverlays.
