### ISSUE TITLE
Build Issue 

### ISSUE THREAD

**Issue by Akrilla** [tizian/Cendric2#2]
I think this perhaps me doing something wrong, but I'm having issues building the project. At first, after compiling the game, after running it gave an error about a missing DLL. I solved this by adding in the  missing SFML DLLs to the executable's directory, however it gave me a new issue: 

```
First-chance exception at 0x0FEC9601 (sfml-graphics-d-2.dll) in Cendric.exe: 0xC0000005: Access violation reading location 0x00000000.
Unhandled exception at 0x0FEC9601 (sfml-graphics-d-2.dll) in Cendric.exe: 0xC0000005: Access violation reading location 0x00000000.

First-chance exception at 0x0FEC9601 (sfml-graphics-d-2.dll) in Cendric.exe: 0xC0000005: Access violation reading location 0x00000000.
Unhandled exception at 0x0FEC9601 (sfml-graphics-d-2.dll) in Cendric.exe: 0xC0000005: Access violation reading location 0x00000000.
```

It breaks at line 12 in Game.cpp.

Any help would be appreciated.

**Comment by eXpl0it3r** [comment]
Sounds like you copied the wrong DLLs. If you built it for x64 make sure to use the x64 DLLs and the other way around.

**Comment by Akrilla** [comment]
Hm, I've tried the x64 bit version of the DLLs now but this is the new error:

```
---------------------------
Cendric.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b).
```

**Comment by Ironbell** [comment]
What is your target platform? If you're using VS and CMake on Windows, make sure that you check Win64 as generator. You can find step-by-step build instructions here: http://cendric.ch/de/code

Let me know if you have further issues, I'm always happy to help. Also, pull now as you'll have a stable version.

**Comment by Akrilla** [comment]
Thanks for the help both of you, after following the instructions I got it fully working. Seems it was just forgetting to configure it as Win64!
