### ISSUE TITLE
Including Cendric in the Solus Linux repository?

### ISSUE THREAD

**Issue by Commander-Zal** [tizian/Cendric2#201]
Greetings Cendric devs! ^_^

As an enthusiast of open-source games, I'm always on the lookout for interesting titles to add into the repository of my favored Linux distro, [Solus](https://solus-project.com/). Upon learning of Cendric from the r/Linux_Gaming subreddit, and that such an impressive looking title was _open-source_, my interest was at an all time peak.

Though Cendric is now officially under the MIT and CC license, I'd like to get your blessing/permission to include the game [into the Solus repos](https://dev.solus-project.com/T6095). Being a somewhat gaming oriented distro, my hope would be that including it in Solus would increase awareness of the game, and by proxy, sales. :)

However, I **totally** understand if you guys aren't comfortable with that, and would prefer the game to only available via your github, steam and Itch.io page. 

Regardless of your decision, thank you for making such a unique game, and for deciding to make it open-source for others to learn from and enjoy.

Cheers! :D

**Comment by Ironbell** [comment]
Heyhey! 
Thanks for your interest, Solus really looks cool. From my side, this is absolutely no problem. My goal is to have more people playing the game, not making the most profit out of it. And I'm especially open when it comes to distributing the Linux version of the game. But let's first wait for @tizian's answer, too.

**Comment by tizian** [comment]
Sounds like a great plan–feel free to add it to the repo!
Best,
Tizian

**Comment by Commander-Zal** [comment]
Wicked! I'll let the Solus devs know it's alright to proceed. Thank you both once again! Seriously appreciate it. ^_^

**Comment by Ironbell** [comment]
Nice! Good luck & Keep us up to date ;)

**Comment by aleksvor** [comment]
@Ironbell @tizian 
Hello! I want to let you know that Cendric 1.1.3 has [landed](https://dev.getsol.us/R4527:ee6221ecbace356921e2347619d3a5fbb1d60321) in Solus Unstable and in a few days will make its way in the stable repo; from now on I will be maintaining Cendric package in Solus. Thank you for the great open source game and permission to distribute it!
