### ISSUE TITLE
Linux Controller.

### ISSUE THREAD

**Issue by chui2ch** [tizian/Cendric2#207]
I am testing the Linux controller support. I have a question about the button layout using a PS4 controller. the O button on the ps4 is set up as attack in the build that I downloaded. It seems like the O button should pick things up. I tried resetting the keybindings to default but it stayed the same. Can I get a screenshot of how I should have my keybindings set up. X seems to also be the default button to open the pause menu. I have the same strange default bindings when using an Xbox one controller. I am running Debian buster. I don't know if that information matters to you all or not.

**Comment by Ironbell** [comment]
If I understand it correctly, your problem is that both the button mapped to Attack and the button mapped to Interact are mapped to the same button per default? Could you attach a screenshot of your gamepad key bindings?

**Comment by chui2ch** [comment]
I'm sorry I was not clear. Here is the default controller layout as it came from the download. The button prompts in game do not match the default layout. For example the game says push O to read a sign. Triangle is the default controller button to interact. Once I read the sign it says that the PS button opens the minimap but the R3 button is the default for this action.
![screenshot_20180614_054301](https://user-images.githubusercontent.com/40251476/41407699-d5e7892e-6f95-11e8-8b85-a76c5df98ed2.png)

One other note when using the Dpad in the over world up and down are inverted. Once I enter on of the platforming areas this is corrected.

**Comment by chui2ch** [comment]
I just tried to change the bindings to match the button prompts, and it is not that they do not match its that the game thinks that the buttons on the PS4 are labeled different. The bumpers and triggers are detected as they should be but the other buttons are not.

Triangle=O
Square= Triangle
X=O
O=X
PS= is labeled as LPush

**Comment by Ironbell** [comment]
Thank you so much for your report too, @chui2ch. I will search for a tool to simulate gamepads and map the buttons accordingly. One interesting thing you mentioned is the DPad flipping. I don't see any reason why it would be like this, the map and level views don't use another input system. They use other movement controls, you cannot move "up" in the level view, this will move the camera up, not the character. 

Anyway, if you want to be mentioned in the credits and get your Steam key for Cendric, drop me a mail: isabelleroesch**at**msn.com

**Comment by Ironbell** [comment]
This is closed now with the new Release [here](https://github.com/tizian/Cendric2/releases/tag/v1.1.0beta2) if you want you can test it again and potentially give me the mappings for your controllers.
