### ISSUE TITLE
Archives should contain a folder with game files instead of just game files

### ISSUE THREAD

**Issue by hardpenguin** [tizian/Cendric2#208]
Both Linux .tar.gz and Windows .zip archives have game files packaged directly at the top directory hierarchy level. This results with polluting the directory used for unpacking the archive as well as confusion if the said directory already contains other files put there by the user.

Game files should be put in a folder before being archived, like this:

```
cendric/
├── db
├── lib
├── res
├── saves
└── Cendric
```

instead of:

```
db
lib
res
saves
Cendric
```

**Comment by Ironbell** [comment]
Good point, I'll change this as soon as I'm on my Linux computer again.

**Comment by Ironbell** [comment]
Updated and the mac version is up too.
