### ISSUE TITLE
Used gamepad button labels/glyphs are confusing

### ISSUE THREAD

**Issue by hardpenguin** [tizian/Cendric2#209]
Usage of PlayStation labels (square, triangle, circle, cross) is absolutely confusing to me since none of my controllers uses those. Could we go with something more generic, like "Button1", "Button4" etc?

Tested with following controllers on Debian GNU/Linux 9 Stretch:
- [Logitech F310](https://www.logitechg.com/en-us/product/f310-gamepad) (Xinput mode, always behaves like a Xbox360 controller)
- [Esperanza EG102](http://esperanza.pl/esperanza-vibration-gamepad-usb-warrior,176,449.html) (recognised as Microntek USB Joystick or DragonRise Inc. PC TWIN SHOCK Gamepad)

**Comment by Ironbell** [comment]
The problem hereby is that these labels should be as short as possible. They are used in various places in the game, labelling slots or simple interactions.
"<X> to open"
seems better to me as
"<Button1> to open"
Maybe we could just label the keybindings like this:
Button1 (X)
Button2 (O)
etc.?

**Comment by hardpenguin** [comment]
> The problem hereby is that these labels should be as short as possible. They are used in various places in the game, labelling slots or simple interactions.

The thing is, those don't match my controller at all. For example:
- it says "O to open"
- but the actual button press is the leftmost action button (the one that would be X on Xbox controller or square on DualShock)

**Comment by Ironbell** [comment]
Good point. I couldn't test at all with a DualShock controller, so I'm happy to fix the mapping. For this purpose, could you give me the default mapping for DualShock like this:
* Default Interact would be Square instead of Circle 
* Default Attack would be ?
* Default Jump would be ?
* Default Back/Escape would be ?
(those are all 4 buttons)

**Comment by Ironbell** [comment]
for now, it is like this:
XBox (tested)
Button 1 => A (Jump)
Button 2 => B (Attack)
Button 3 => X (Confirm, Interact)
Button 4 => Y (Back, Escape)

DS4 (Untested)
Button 1 => Square (Jump)
Button 2 => Cross (Attack)
Button 3 => Circle (Interact, Confirm)
Button 4 => Triangle (Back, Escape)

**Comment by Ironbell** [comment]
This is closed now with the new Release [here](https://github.com/tizian/Cendric2/releases/tag/v1.1.0beta2) if you want you can test it again and potentially give me the mappings for your controllers.
