### ISSUE TITLE
Cannot use the same gamepad button to two different actions

### ISSUE THREAD

**Issue by hardpenguin** [tizian/Cendric2#210]
It seems like I wasn't able to assign the same button to two different actions. Is it really necessary that "Confirm" and "Interact" use different inputs?

Tested with following controllers on Debian GNU/Linux 9 Stretch:
- [Logitech F310](https://www.logitechg.com/en-us/product/f310-gamepad) (Xinput mode, always behaves like a Xbox360 controller)
- [Esperanza EG102](http://esperanza.pl/esperanza-vibration-gamepad-usb-warrior,176,449.html) (recognised as Microntek USB Joystick or DragonRise Inc. PC TWIN SHOCK Gamepad)

**Comment by Ironbell** [comment]
Per default, Interact and confirm are mapped to the same button. Changing the keybinding for interact should also change the keybinding for confirm and vice versa. Is this different for you?
Default for DS4: Circle
Default for Xbox: X

**Comment by hardpenguin** [comment]
My bad, after restarting the game and re-plugging the controller the issue seems to be gone. I think I reported it due to the glyph confusion reported here: https://github.com/tizian/Cendric2/issues/209
