### ISSUE TITLE
Testing report with gamepads on Linux (1.1.0 beta 1)

### ISSUE THREAD

**Issue by akien-mga** [tizian/Cendric2#211]
I've seen that @hardpenguin already opened #209, but to keep reports focused I'm opening a new issue for my results. What I experience might eventually be the same issues as those in #209 though.

Testing environment:
- Mageia 6 x86_64 (Linux), kernel 4.14.44, nvidia GTX 670MX with latest proprietary drivers
- Cendric 1.1.0 beta 1, Ubuntu build

-----

## Test 1: Steam Controller in Xbox 360 controller mode

Running outside of Steam, set to Xbox 360 controller mode via the [sc-controller](https://github.com/kozec/sc-controller) application. Testing in this [Godot joypad demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads), all buttons and axes are properly recognized with their correction position. (Godot's joypad support relies on SDL2 mappings).

![screenshot_20180614_115603](https://user-images.githubusercontent.com/4701338/41405434-0a966fc6-6fca-11e8-9590-2670a7ccf1b2.png)

In Cendric, the default mappings are the following:
![screenshot_20180614_115807](https://user-images.githubusercontent.com/4701338/41405521-34bc419a-6fca-11e8-9626-d60787d14d3c.png)

Though they use the Xbox A, B, X, Y, none of those seem to work out of the box with this controller. The D-Pad and the directional axis work though.

If I remap the keys to what they are supposed to be (i.e. Y on the controller for Exit, etc.), I get:

![screenshot_20180614_120027](https://user-images.githubusercontent.com/4701338/41405651-880c0a74-6fca-11e8-9888-64b4e7b42dd5.png)

i.e. the Xbox 360 controller keys are displayed as PlayStation-style keys which don't map my controller. When I press "start" for the "Menu" key, it assigns "RT" (and unassigns "Quick Slot 2").
If I try to reassign "Quick Slot 1" and "Quick Slot 2" to the "LT" and "RT" buttons, it shows an error that those buttons are reserved.

Here's the equivalence between what I pressed and what was shown:

| Pressed | Shown |
| ---------- | --------- |
| Y | Triangle ✓ |
| X | Round ✗ |
| A | Square ✗ |
| B | Cross ✗ |
| LT | *Error* ✗ |
| RT | *Error* ✗ |
| LB | LB ✓|
| RB | RB ✓ |
| Start | RT ✗ |

So apart from the wrong symbols used, it's also the wrong position displayed, apart from Y <> Triangle which happen to be a good match.

With that config saved, I can play normally: A is jump, B is attack, X is interact and Y is pause. I can't get the inventory displayed (which I guess is what "Menu" would do?).

So there seems to be some mismatch between the actual keys recognized and what Cendric/SFML displays as their names.

## Test 2: CSL Gamepad for PS3 / PC

This one is a relatively cheap PS3-like USB gamepad, and I wouldn't be surprised if it doesn't have proper mappings for SFML. In the above-mentioned Godot demo it has proper mappings, the buttons pressed match the ones highlighted in the demo (controller identified as GreenAsia Inc. USB Joystick).

It's a PS-style controller so with Cross (bottom), Round (right), Triangle (top), Square (left).

Testing Cendric with a blank config. The default bindings don't work (same as for the SC Controller above), so changing them to what they would be on the Xbox 360 controller gives:

![screenshot_20180614_120827](https://user-images.githubusercontent.com/4701338/41406062-a636c812-6fcb-11e8-9bc0-ede0309098ff.png)

Here it shows PS-like symbols as expected, but not the right ones for the keys pressed.
Here's the conversion of what I pressed and what was shown:

| Pressed | Shown |
| ---------- | --------- |
| Triangle | Square ✗ |
| Square | Triangle ✗ |
| Cross | Round ✗ |
| Round | Cross ✗ |
| LT | LT ✓ |
| RT | RT ✓ |
| LB | LB ✓|
| RB | RB ✓ |
| Start | Options ✗ |

With that config saved I can play properly, and all actions seem functional (including "Menu" on Start (shown as "Options") which brings up the inventory.

Next test would be the Steam Controller when loading the game in Steam directly, and configuring via Steam for Xbox 360 style bindings, but I'll leave that for later.

**Comment by akien-mga** [comment]
In case it could be useful, here's the above-mentioned Godot joypads demo which I'm using to check the gamepads support before testing them in Cendric: [joypads-test.zip](https://github.com/tizian/Cendric2/files/2101903/joypads-test.zip) (contains Windows and Linux 64-bit debug binaries from Godot 3.0.3)

**Comment by Ironbell** [comment]
That's a pretty solid report, thank you so much for this. It's interesting that even though I just mapped Xbox and DS4 controllers, others seem to partly work. I just don't know exactly which axis maps to which button on which gamepad, so I might drop the PS symbols completely and  replace them with B1 to B4. 

That's one solution, another one would be to find a tool simulating different gamepads so I could try it out and map them accordingly. 

Thanks a lot for your effort @akien-mga. If you want to be mentioned in the credits for it and get your well deserved Steam key, drop me a mail: isabelleroesch<at>msn.com.

**Comment by Ironbell** [comment]
This is closed now with the new Release [here](https://github.com/tizian/Cendric2/releases/tag/v1.1.0beta2) if you want you can test it again and potentially give me the mappings for your controllers.
