### ISSUE TITLE
Compilation error on linux

### ISSUE THREAD

**Issue by mnhauke** [tizian/Cendric2#213]
I've just tried to compile the master branch on a openSUSE machine and the build fails with

> src/Platform/CendricLinux.cpp:37:9: error: 'RESDIR' was not declared in this scope

```
...
[  173s] /home/abuild/rpmbuild/BUILD/cendric-1.1.0beta2.11/src/Platform/CendricLinux.cpp: In function 'std::__cxx11::string getSystemResourcePath()':
[  173s] /home/abuild/rpmbuild/BUILD/cendric-1.1.0beta2.11/src/Platform/CendricLinux.cpp:37:9: error: 'RESDIR' was not declared in this scope
[  173s]   return RESDIR;
[  173s]          ^~~~~~
[  173s] /home/abuild/rpmbuild/BUILD/cendric-1.1.0beta2.11/src/Platform/CendricLinux.cpp:37:9: note: suggested alternative: 'EISDIR'
[  173s]   return RESDIR;
[  173s]          ^~~~~~
[  173s]          EISDIR
...
```
Here's the full buildlog from openSUSE Leap 15.0:
[cendric-leap15-buildlog.txt](https://github.com/tizian/Cendric2/files/2238732/cendric-leap15-buildlog.txt)

**Comment by Ironbell** [comment]
Did you use CMake for it? In that file, the RESDIR is defined as "share/Cendric". The default for the RESDIR is usually just "res".

In CendricLinux.cpp, replace the RESDIR with "res".

**Comment by mnhauke** [comment]
I finally found the culprit...
if (!APPLE) seems not to be a valid CMake syntax

Here's the fix:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c1cd16b..0cfe0ee 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -193,7 +193,7 @@ if (WIN32 AND CENDRIC_BUILD_DIALOGUE_TOOL)
 
 endif()
 
-if (!APPLE)
+if (NOT APPLE)
     set(RESDIR "share/Cendric" CACHE STRING "Directory Game Ressources are installed to")
     set(BINDIR "bin" CACHE STRING "Directory Game Binary is installed to")
```

**Comment by Ironbell** [comment]
You're right, it should work out of the box with the CMake settings. I didn't find it myself because I use a different CMake file for Linux builds. Thank you so much for the fix! <3

**Comment by mnhauke** [comment]
Your're welcome :-)
