### ISSUE TITLE
Sell game on GOG

### ISSUE THREAD

**Issue by Jacalz** [tizian/Cendric2#215]
I think your great retro inspired game could be a great game to join Good Old Games also referred to  as [GOG](https://gog.com). It would be a great way to get your game DRM free from a trusted platform where it can be preserved for future generations to enjoy.

Thanks for considering this and thanks for a great game 👌

**Comment by Ironbell** [comment]
Thanks for your kind words! I actually considered it to put it on GOG, but it wasn't popular enough to get on there, which is a shame. Maybe I should try again. For now, it is also available DRM free on itch.io. (https://ironbell.itch.io/cendric), but  there's not the latest version up there.
