### ISSUE TITLE
Minor annoyance in beer price

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#216]
In The River Inn, you can buy infinite beers for 10g each, but you can get a total of 10 beers for 8g from the normal trading window. 
I see no reason for him having infinite beers, but finite of the same sort at the same time. And when they do not cost the same either, it's shady business...

Make the infinite beer at The River Inn cost 2g less, and remove the finite beer from the trading window?
Or make the finite beer have a lower buff (since it's priced lower)?

**Comment by Ironbell** [comment]
@OGwold Valid point. I'll remove the beer from his trading items and only keep the ones you get via dialogue. (will only work with new games, as old ones save the trading items per merchant).
