### ISSUE TITLE
Anti magic crystal/beams

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#217]
"Light" is not negated by goingh through a anti magic beam (the one in the secret library)
What are supposed to be negated be theese?

**Comment by Ironbell** [comment]
@OGwold the beam in the library should make sure that the puzzle is solved the intended way (ice block crushed by the thwomp and not by a fireball from below). Light is a non-intrusive spell and does not interact with anything. I see your point that it should be killed lore-wise but gameplay wise, it's not a problem.
