### ISSUE TITLE
Dead enemy physics

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#219]
When a corpse land on a up/down moving platform the body will float.

![image](https://user-images.githubusercontent.com/33553242/50007106-18c9b780-ffb0-11e8-8b5a-b95557801802.png)

**Comment by OGwold** [comment]
Also, I add this here because you really won't care: But I can fire spells wherever I want, even when holding two anti-magic crystals in my pockets. 
Unlikely...

**Comment by Ironbell** [comment]
@OGwold Pendants (really, every armor in every game, like ever) only have effects on you when you wear them. Did you not pay attention in magic school? The crystal (yes, even two of them) is too small to have an effect on you if it's in your backpack and not close to your skin.

**Comment by Ironbell** [comment]
also, the body floats here because it's on an 'evil tile'. Not because of the moving platform. Enemies avoid evil tiles, even when dead. that's why it also floats on the water. Pls reopen if it really floats on a moving platform.
