### ISSUE TITLE
Skeleton in the crypt wasn't there [can't reproduce]

### ISSUE THREAD

**Issue by eXpl0it3r** [tizian/Cendric2#22]
**When**: Chapter 1
**Where**: The crypt
**How**: Start the game fresh, get the quest from Robert and go into the crypt

I started the game fresh and got into the crypt for the first time and the skeleton wasn't there. Which also means that I could simply walk to the exit without having to fight the skeleton.

When I walk back into the cave again, for a split second I saw the skeleton and then I saw its body to loot on the ground.

I tried to replay things pretty much the way I did the first time. I even reinstalled the game freshly, but couldn't reproduce the issue. Since I was writing other reports the game ran for a while already, maybe there's some timing issue going on?

Maybe others will run into this and maybe we can find a common common denominator. 😉 

Things I had on me:

* Sword (equipped)
* Silver ring (equipped)
* Silkweed
* Staff thingy
* Walking pole
* Various loot

**Comment by Ironbell** [comment]
might be fixed. pls reopen if it happens again.
