### ISSUE TITLE
Have you made a map editor or a character editor? How to manage the huge amount of characters and map resources ? 

### ISSUE THREAD

**Issue by clw5180** [tizian/Cendric2#225]
Dear Ironbell,
After four hours work, I finally compiled this file successfully on VS2017 (there seems to be some problems with the sfml lib that you provided on github : )  I have to say that I am so lucky to find this excellent and grand 2D game project! 
Now I want to make my own 2d rpg game, so maybe I will debug your game to learn something recently. But I'm curious whether you've made a map editor or character editor like RPG-maker ? How you manage the huge amount of characters and map resources ?

**Comment by Ironbell** [comment]
Hey @clw5180 
Sorry for the late response, the notification went straight into my Junk Mail folder.
Cendric uses Tiled (https://www.mapeditor.org/) as a map editor. There is no character editor like RPG maker, all the faces and sprite sheets for characters are hand-made.
There is a resource manager in the code which loads and unloads resources, so not all images are loaded into memory at the same time.

Hope that helps and good luck with your game!

Best,
Ironbell
