### ISSUE TITLE
Fullscreen only on first screen

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#23]
Fullscreen is only avaible on the first monitor.

**Comment by Ironbell** [comment]
Probably a SFML issue. Windows, Dual-Screen?

**Comment by Randalf98** [comment]
Windows 10, 3 Monitors, GTX 970, only on main display.

**Comment by eXpl0it3r** [comment]
Yeah, SFML 🙂

**Comment by Ironbell** [comment]
We won't fix this issue as long as fullscreen is working on the primary monitor.
