### ISSUE TITLE
Fullscreen sets screen resolution to 1280x720

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#24]
Fullscreen sets monitor resolution to 1280x720, which causes some strange visuals on the other monitors.

**Comment by Ironbell** [comment]
Setting: Fullscreen or setting: Windowed Fullscreen?

**Comment by Ironbell** [comment]
To work around this for now, use the window setting but click on the fullscreen button of the window.

**Comment by Randalf98** [comment]
Just "Fullscreen" problem, "Windowed Fullscreen" works without that problem.
Yes doing it like that.

**Comment by Ironbell** [comment]
This is fixed by now, using a texture scaling instead of window scaling. Please reopen if it persists on a specific system.
