### ISSUE TITLE
Alt Tab doesn't really work.

### ISSUE THREAD

**Issue by Auronit** [tizian/Cendric2#33]
When playing a game I often find myself Alt-Tabbing out of it. This is a little messed up here, as the screen is suddenly very compromised (there's a huge black border, so not just the resolution has gone down btu the actual screen size.

**Comment by Ironbell** [comment]
What's your OS and setup? (monitor-wise)

**Comment by Ironbell** [comment]
Thank you. Playing in full screen or full window or windowed fullscreen mode? :P

**Comment by Auronit** [comment]
I was playing in fullscreen there. Windowed is fine

**Comment by Ironbell** [comment]
Alt-Tab works fine for me (Windows 10). As I can't reproduce it on my system and it's an annoying but rather small problem, I will look at it only if there's enough time before the release

![unbenannt](https://user-images.githubusercontent.com/9303244/33235555-a854c056-d23a-11e7-9f5a-6e8fec6309a0.png)

**Comment by Ironbell** [comment]
Auronit, I need your email address for your points :)

**Comment by Auronit** [comment]
sikiobasel@gmail.com

Terribly sorry, I've had some rough weeks.

**Comment by Ironbell** [comment]
I will close this as this seems to be no longer an issue. Feel free to reopen if it occurs (and specify the system specs).
