### ISSUE TITLE
A space too much?

### ISSUE THREAD

**Issue by Auronit** [tizian/Cendric2#37]
Really not sure about that one but in the dialogue with Robert in the German version, he says "Aber ich bräuchte diesen Stein wirklich!" Es sieht aus als wäre zwischen "diesem" und "Stein" ein Leerschlag zuviel. Könnte aber auch einfach optisch sein.

**Comment by Ironbell** [comment]
There's a database test that checks for that.

![image](https://user-images.githubusercontent.com/9303244/32632132-bde1448e-c5a2-11e7-9b14-f376cc9ec10c.png)

Ok you're correct. I'll fix the other ones as well

**Comment by Ironbell** [comment]
There's not one double space left in all of the game's texts now ;)
