### ISSUE TITLE
Missing Clicking Sound (Dialogue)

### ISSUE THREAD

**Issue by Auronit** [tizian/Cendric2#38]
At some point the clicking sound when selecting dialogue was completely gone. I only noticed when it reappeared after the cutscene with the elder. I'll see if I can recreate it or if it happens again.

**Comment by Ironbell** [comment]
Currently not reproducible. The sound only appears when you switch a dialogue option, not select one. Should it be on select as well?

**Comment by Ironbell** [comment]
I'll close this for now. If it happens again, please reopen.
