### ISSUE TITLE
Click-Attack stopped working

### ISSUE THREAD

**Issue by Auronit** [tizian/Cendric2#39]
I entered the Level where you cross the ruined bridge from the side of the tavern but then in the level couldn't swing my sword by clicking with the mouse. Is fixed by swinging with "F" once.

**Comment by Ironbell** [comment]
Click always goes onto the currently selected spell. Maybe, the ice bolt was selected. Can you reproduce it?

**Comment by Auronit** [comment]
I can try. I had Sword equipped though.

**Comment by Auronit** [comment]
Good news, i can recreate it. I have a save that I can always load with the issue. I load the save, go to the level and can't use the sword by clicking. Do you want the save and if yes, how do I go about that?

**Comment by Auronit** [comment]
It actually doesn't matter which level I enter, I can't use the Sword by clicking until I hit F. I saved right befoer approaching the "Monster" (werewolf) btu I don't know what could have triggered it,

**Comment by Ironbell** [comment]
Alright, I'll look into it. Thank you!

**Comment by Auronit** [comment]
Can I give you the save? Does that help?

**Comment by Ironbell** [comment]
You can attach it here if you want. I should be able to reproduce it though ;)
