### ISSUE TITLE
Respawn mechanism is making things to easy

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#43]
When you respawn after you died or pressing "B".
Objects like Iron Ore instantly respawn.
And if you die from the skeleton out of the coffins, the skeletons despawns.

**Comment by Ironbell** [comment]
The iron ore is intended, farming it won't bring you more gold but you need it for some quests. We could change the coffin skeletons though in a way that you'll have to kill them first to loot  the coffin.

**Comment by Ironbell** [comment]
It's a game mechanic. We won't change this.
