### ISSUE TITLE
Cooking multiple Items at once

### ISSUE THREAD

**Issue by Sansumaki** [tizian/Cendric2#50]
When you will cook 50 or more meat  at once you must click 50 times.

Maybe there should be an option cook all.

**Comment by Ironbell** [comment]
well, it's a reference to the first gothic games, where you had to cook REALLY LONG until you get one piece of roasted meat. Be happy that it only takes one click (or even enter/e works). But I'll look into it, maybe in the polish phase :)

**Comment by Ironbell** [comment]
It's a feature, as it's a reference. Also, cooking is really fast. Cooking everything at once would take away the fun.
