### ISSUE TITLE
Chronology issue

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#53]
I killed the wolf boss before speaking to the paladins and Inina.
In the dialogue she tells me about the magic that weakens the shrine, even though the boss is already dead. Right after she tells me that she feels that that magic is gone.
This isn't a gamebreaking issue, but it feels weird in the story. Maybe the boss room should only be available after speaking to Inina?

**Comment by OGwold** [comment]
I agree. It looks weird. My suggestion on a fix could be:
Have another dialogue if the boss is beaten, where she already felt the magic leave. 
Or, make Inina give you a key to open the door to the crystal crypt.

**Comment by Kylaine** [comment]
Having Inina give you a key would raise other questions. Why would she have a key to that crypt?
An alternate dialogue would probably be the smoothest thing to do.

**Comment by Ironbell** [comment]
Yes, an additional dialogue would be good here. I want to keep this possibility for the player.
