### ISSUE TITLE
The ascendence(Der Aufstieg) Sound Bug

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#54]
Sound Bugs like it's playing a sound and resets it every 0.1s.

Never happend bevor and twice there.
First time I activated a crystal on a spell.
Second time I revived a Lava ghost.

Dissapears while dragging around the window, after that it starts again.
Stops completly when leaving the area,

**Comment by Randalf98** [comment]
Had it again, down left there was a slime and after I killed it it occured while the 'corpse' was in sight. After picking it up the sound dissapeared.

**Comment by Ironbell** [comment]
Might have been fixed. Please reopen if it occurs again.
