### ISSUE TITLE
Game Crash After specific Spell

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#56]
The Game Crashs in the garden of the castle, after I have used the summon spell for a gargoyle with all enhancments on level 3.
I could recreate it with just summoning the gargoyle again. My autosave is attached. Hope it helps.
Here are my specifications atm:
Windows 10
Intel i7 4790k
GTX980
16 GB DDR3 RAM

Game is installed on D:\
Running it on Windowed Mode on a 2560x1440 screen.

If you need anything else just write it.

[autosave.zip](https://github.com/tizian/Cendric2/files/1462793/autosave.zip)

**Comment by Randalf98** [comment]
Definitly the Gargoyle, after launching the gargoyle against the books, while hunting the king.
I will try it out now without modifiers.

**Comment by Randalf98** [comment]
Additional information, it didn't occured on resurrected gargoyles.

**Comment by Ironbell** [comment]
I'll find that, no worries ;)
