### ISSUE TITLE
Missing character and writing mistake

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#59]
Talking to Vincent about the delivery of alcohol to the oldest.
Current: "... das erste mal, ... er betrinkt sich eifach gern von Zeit zu Zeit."
Correct: "... das erste Mal, ... er betrinkt sich einfach gern von Zeit zu Zeit."

EDIT 1:
Later on
Current: "kleine... Überaschung bereiten?"
Correct: "kleine... Überraschung bereiten?"

EDIT 2:
Later when disagree with his offer.
Current: ".. wird wohl immer die richtige sein. ..."
Correct: ".. wird wohl immer die Richtige sein. ..."

Won't open new issues for mistakes in the same dialog.

**Comment by Ironbell** [comment]
granted you 3p for this ;)
