### ISSUE TITLE
Walking animation issue in the inn

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#60]
In the inn outsite the city, when you walk against some furniture. It looks like you run on the place super fast against it. Looks pretty wierd and doesn't go on every furniture.

**Comment by Ironbell** [comment]
Could you specify the exact furniture?

**Comment by Randalf98** [comment]
Sure, all are marked with a red arrow.
Additionally you can walk halfway through the left wall.

![innfurniture](https://user-images.githubusercontent.com/12735077/32683314-99b334d6-c67a-11e7-8b7d-c97e4cef55b2.PNG)

**Comment by Randalf98** [comment]
More found in Syrah's House, should I search for more or is that enough information for the moment?

![syrahhouse](https://user-images.githubusercontent.com/12735077/32683400-35b29f98-c67b-11e7-8a0e-5bff745216a3.PNG)

**Comment by Ironbell** [comment]
It is, thank you. Probably the same problem everywhere anyway.

**Comment by Ironbell** [comment]
Not reproducible for me. Could you try it out on the new beta version? VSync enabled/disabled?

**Comment by Randalf98** [comment]
It appears only with VSync dissabled. Week 2 Build.

**Comment by Ironbell** [comment]
Interesting.

**Comment by Ironbell** [comment]
I tried this with VSync enabled and disabled and couldn't see it. I'm sorry, I  can't fix what I can't see. Maybe you need to show it to me on your pc...
