### ISSUE TITLE
Stuck in wall

### ISSUE THREAD

**Issue by RaymonWe** [tizian/Cendric2#64]
In Chapter 1 below the village I got stuck in the wall. I was able to reproduce this by just repeatedly running against the wall.
![2017-11-11 00-26-33](https://user-images.githubusercontent.com/33033939/32684253-2e280112-c682-11e7-88bf-4fe402bc1dda.png)

**Comment by Ironbell** [comment]
I can't reproduce it on my pc. It is intended that cendric is behind the wall here. Were you stuck in a sense that you couldn't move anymore (not up, not right) in this situation? Left and down are locked here.

**Comment by RaymonWe** [comment]
Yes I couldn't move at all. Here is my save file.
[1510356439ich steck fescht.zip](https://github.com/tizian/Cendric2/files/1489194/1510356439ich.steck.fescht.zip)

**Comment by Ironbell** [comment]
Merci :dagger:  ganz nice.

**Comment by Ironbell** [comment]
I adjusted that collision triangle (it was a bit ugly aligned). But I couldn't reproduce it, neither before or after the fix. If this or similar happens again, pelase reopen.
