### ISSUE TITLE
Crushing a mushroom locks like crushing block

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#68]
When crushing a mushroom it turns into a block and gets crushed as a mushroom.

![crushingmushroom](https://user-images.githubusercontent.com/12735077/32689511-9f96081c-c6e6-11e7-8419-08001ead86d5.PNG)

**Comment by Ironbell** [comment]
I was just too lazy to create another animation. The same crushing animation is used for wind blocks as well.

**Comment by Ironbell** [comment]
![crush](https://user-images.githubusercontent.com/9303244/33240657-0b20077a-d2ba-11e7-99ec-35a22b0d6cd7.gif)
