### ISSUE TITLE
Ring of the sunblade

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#70]
The Item show the stats in two sets of parenthesis'
![knlosa](https://user-images.githubusercontent.com/33553242/32690269-854810aa-c6f4-11e7-9b80-24a47b1886f0.png)

**Comment by Ironbell** [comment]
All rings do, as they are compared with both other equipped rings.

**Comment by OGwold** [comment]
Thought I checked that yesterday when i found it...
