### ISSUE TITLE
Jason textbox

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#72]
Jason have duplicate lines of both items he can make. Choosing one option will make both with the same text disappear, leaving duplicates of the remaining weapon.
![134](https://user-images.githubusercontent.com/33553242/32690478-bf815f58-c6f7-11e7-945f-ce2c71e78c66.png)

**Comment by Ironbell** [comment]
It's not duplicated, one is fiery and one is dark, which results in another skin and other stats. They will disappear because they cannot be crafted anymore (weapon not in inventory)
