### ISSUE TITLE
Graphic Error

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#73]
One some points you walk behind some layers or stand in front of some layers you shouldn't. Some examples below, if I should search for more, then notice me.

![graphicissue4](https://user-images.githubusercontent.com/12735077/32690656-57ff8ae6-c6fa-11e7-8514-eae0ed392d16.PNG)
![graphicissue3](https://user-images.githubusercontent.com/12735077/32690657-5816768e-c6fa-11e7-9127-23224f5b93e8.PNG)
![graphicissue2](https://user-images.githubusercontent.com/12735077/32690658-582c9ac2-c6fa-11e7-8d9e-6a5e574c406f.PNG)
![graphicissue1](https://user-images.githubusercontent.com/12735077/32690659-5842af74-c6fa-11e7-9fc0-c20ce3759eef.PNG)
![graphicissue](https://user-images.githubusercontent.com/12735077/32690660-585864d6-c6fa-11e7-9e1f-5e4f77bd8877.PNG)

**Comment by Ironbell** [comment]
each clipping tile will grant you 1p so it's up to you whether to search or not ;) thank you, that's already +5

**Comment by Randalf98** [comment]
*cough
I tried to get just one screenshot per object, hope it helps and isn't too annoying :D 
*Bursts into laughter :D 

![clippingtile08](https://user-images.githubusercontent.com/12735077/32691180-d40de534-c703-11e7-9602-42d9be480ccb.PNG)
![clippingtile07](https://user-images.githubusercontent.com/12735077/32691181-d4246a16-c703-11e7-936b-3a74f0d4d114.PNG)
![clippingtile06](https://user-images.githubusercontent.com/12735077/32691182-d43c72a0-c703-11e7-8a85-3a15e4672268.PNG)
![clippingtile05](https://user-images.githubusercontent.com/12735077/32691183-d453e480-c703-11e7-8cb5-e5e2d4272ebd.PNG)
![clippingtile04](https://user-images.githubusercontent.com/12735077/32691184-d46b8428-c703-11e7-9968-6805267d1d62.PNG)
![clippingtile03](https://user-images.githubusercontent.com/12735077/32691185-d4861450-c703-11e7-8d0f-cbfbbdd69fe1.PNG)
![clippingtile02](https://user-images.githubusercontent.com/12735077/32691186-d49e025e-c703-11e7-9986-1e959ce04491.PNG)
![clippingtile13](https://user-images.githubusercontent.com/12735077/32691175-d384ab02-c703-11e7-82d6-4ac24149d4c9.PNG)
![clippingtile12](https://user-images.githubusercontent.com/12735077/32691176-d39c1d3c-c703-11e7-8b04-170c38a17775.PNG)
![clippingtile11](https://user-images.githubusercontent.com/12735077/32691177-d3bb4d2e-c703-11e7-80ed-88e5be0009c2.PNG)
![clippingtile10](https://user-images.githubusercontent.com/12735077/32691178-d3d23a52-c703-11e7-8fe8-f1e7e382638e.PNG)
![clippingtile09](https://user-images.githubusercontent.com/12735077/32691179-d3eb9eca-c703-11e7-9386-7c7d4283cf6a.PNG)
![clippingtile01](https://user-images.githubusercontent.com/12735077/32691146-d07c73ea-c703-11e7-8657-32f75562549f.PNG)
![clippingtile41](https://user-images.githubusercontent.com/12735077/32691147-d09367da-c703-11e7-99cb-c8760739cf29.PNG)
![clippingtile40](https://user-images.githubusercontent.com/12735077/32691148-d0a9a3a6-c703-11e7-92e9-87da695f34b3.PNG)
![clippingtile39](https://user-images.githubusercontent.com/12735077/32691149-d0c113b0-c703-11e7-90c3-dade14046628.PNG)
![clippingtile38](https://user-images.githubusercontent.com/12735077/32691150-d0d75abc-c703-11e7-8ab5-8eab1299e6b2.PNG)
![clippingtile37](https://user-images.githubusercontent.com/12735077/32691151-d0f3aa32-c703-11e7-9b37-cd5558ccc0b8.PNG)
![clippingtile36](https://user-images.githubusercontent.com/12735077/32691152-d10a4f8a-c703-11e7-8c67-96b4c4054f0e.PNG)
![clippingtile35](https://user-images.githubusercontent.com/12735077/32691153-d1210dc4-c703-11e7-848e-1c137089052c.PNG)
![clippingtile34](https://user-images.githubusercontent.com/12735077/32691154-d137b3e4-c703-11e7-927f-dc57161f9fec.PNG)
![clippingtile33](https://user-images.githubusercontent.com/12735077/32691155-d155a0e8-c703-11e7-80f8-d3e74c9a0964.PNG)
![clippingtile32](https://user-images.githubusercontent.com/12735077/32691156-d179801c-c703-11e7-93c3-bc825315bb06.PNG)
![clippingtile31](https://user-images.githubusercontent.com/12735077/32691157-d1907a2e-c703-11e7-89ef-018d69dc34d9.PNG)
![clippingtile30](https://user-images.githubusercontent.com/12735077/32691158-d1a7b73e-c703-11e7-9b3e-7bf30d319f9a.PNG)
![clippingtile29](https://user-images.githubusercontent.com/12735077/32691159-d1bf84c2-c703-11e7-9eb0-ded567f4c55a.PNG)
![clippingtile28](https://user-images.githubusercontent.com/12735077/32691160-d1d9b0b8-c703-11e7-8823-680c623df76d.PNG)
![clippingtile27](https://user-images.githubusercontent.com/12735077/32691161-d1f12e00-c703-11e7-9c75-e88d762df6b3.PNG)
![clippingtile26](https://user-images.githubusercontent.com/12735077/32691162-d211ce08-c703-11e7-9777-dfd503a081df.PNG)
![clippingtile25](https://user-images.githubusercontent.com/12735077/32691163-d22bdb04-c703-11e7-93f0-91603463a157.PNG)
![clippingtile24](https://user-images.githubusercontent.com/12735077/32691164-d24532b6-c703-11e7-94ec-99db63e00ea4.PNG)
![clippingtile23](https://user-images.githubusercontent.com/12735077/32691165-d2614c94-c703-11e7-85a1-d4cf1916732e.PNG)
![clippingtile22](https://user-images.githubusercontent.com/12735077/32691166-d27b6bba-c703-11e7-98f9-67ba027d6536.PNG)
![clippingtile21](https://user-images.githubusercontent.com/12735077/32691167-d295447c-c703-11e7-8b85-fb09d83bb042.PNG)
![clippingtile20](https://user-images.githubusercontent.com/12735077/32691168-d2b4d6b6-c703-11e7-8c05-9f6fcef9f371.PNG)
![clippingtile19](https://user-images.githubusercontent.com/12735077/32691169-d2d0012a-c703-11e7-96d7-e546819ca153.PNG)
![clippingtile18](https://user-images.githubusercontent.com/12735077/32691170-d2e9793e-c703-11e7-8274-07e7b8b64b9e.PNG)
![clippingtile17](https://user-images.githubusercontent.com/12735077/32691171-d301b274-c703-11e7-98e0-05afed6f2234.PNG)
![clippingtile16](https://user-images.githubusercontent.com/12735077/32691172-d31a6382-c703-11e7-96c4-ade43f01d130.PNG)
![clippingtile15](https://user-images.githubusercontent.com/12735077/32691173-d332812e-c703-11e7-9b85-48dfb08645b9.PNG)
![clippingtile14](https://user-images.githubusercontent.com/12735077/32691174-d34abfe6-c703-11e7-8040-51ca941e9f8c.PNG)

**Comment by Randalf98** [comment]
I found some more.

![clippingtile44](https://user-images.githubusercontent.com/12735077/32694679-9418756e-c746-11e7-8b52-b0e2547b281c.PNG)
![clippingtile43](https://user-images.githubusercontent.com/12735077/32694680-942f978a-c746-11e7-95c8-1473992e6020.PNG)
![clippingtile42](https://user-images.githubusercontent.com/12735077/32694681-94458a68-c746-11e7-8545-16a225de5734.PNG)
![clippingtile52](https://user-images.githubusercontent.com/12735077/32694682-945c7f52-c746-11e7-96e9-c4638800a1de.PNG)
![clippingtile51](https://user-images.githubusercontent.com/12735077/32694683-94736d48-c746-11e7-8079-39ccf4dc3e94.PNG)
![clippingtile50](https://user-images.githubusercontent.com/12735077/32694684-9489903c-c746-11e7-8663-41fdb85ba8bf.PNG)
![clippingtile49](https://user-images.githubusercontent.com/12735077/32694685-94a171fc-c746-11e7-9832-067ee41774de.PNG)
![clippingtile48](https://user-images.githubusercontent.com/12735077/32694686-94bba6d0-c746-11e7-903b-f6ab9075753b.PNG)
![clippingtile47](https://user-images.githubusercontent.com/12735077/32694687-94d1cabe-c746-11e7-8037-c1548609523a.PNG)
![clippingtile46](https://user-images.githubusercontent.com/12735077/32694688-94ee71fa-c746-11e7-9c7e-397bd8e9cc05.PNG)
![clippingtile45](https://user-images.githubusercontent.com/12735077/32694689-9560edde-c746-11e7-93ba-0c9f9df5e9ea.PNG)

**Comment by Ironbell** [comment]
57 clipping tiles, I'm impressed. That's gonna take one hour or so.

**Comment by Ironbell** [comment]
I now  will keep cendric's shadow inside his hitbox. makes things more easy and also neat.

![image](https://user-images.githubusercontent.com/9303244/32698784-4d7faa04-c7ab-11e7-8543-c526a0699d8b.png)
