### ISSUE TITLE
Broken shadow on the entrance of the tempel.

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#76]
Broken shadow on the entrance of the tempel.

![brokenshadow](https://user-images.githubusercontent.com/12735077/32691255-f6488676-c704-11e7-9d4c-baeee26d2970.PNG)

**Comment by Ironbell** [comment]
The shadow is meant to be hard. What do you mea?

**Comment by Randalf98** [comment]
Shadow of the entrance is a strange when the player shadow can fall in.

**Comment by Ironbell** [comment]
It's something that can't be handled by the engine as those shadows are only sprites that are drawn on top of each other. In real life, overlapping shadows also create a darker shadow (if there are several light sources), so it's ok.
