### ISSUE TITLE
logic problem

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#78]
When I talk to Paladin Steven after finding his helmet, he asks me to give it to him. I tell him to give me the letter first. He gives me the letter and asks for his helmet again. I then decide to give it to him.
After, he again "gives" me the letter.

**Comment by Ironbell** [comment]
Did you receive the letter twice then? I'll look into it.

**Comment by Kylaine** [comment]
I only received the letter once. It's just a weird dialogue.
