### ISSUE TITLE
Graphical error while dying

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#79]
Sometimes there's two sprites on top of each other when you die. It looks like it's one player sprite with clothes on, and one without clothes being rendered on top of each other, but they are at different places in the animation. 
While you die you have 4 feet, two with clothes, and two without. I can't remember if it affects hands as well, but I'll edit if it does.
I could not get a screenshot of is, since it happen "randomly".

**Comment by Ironbell** [comment]
Does it have to do with anti gravity?

**Comment by OGwold** [comment]
I have not seen it while using Anti Gravity. Most of the time just on the ground, walking normally.

**Comment by Ironbell** [comment]
I think it's a facing left/right problem. Cendric is facing one way and his equipment the other 🙈
