### ISSUE TITLE
spelling error swiss german

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#80]
The error appears in the dialogue with Jonathan after learning the fire ball spell. When asking about the "Dämmerigsmagie" he says: "Magier wo sich mit Dämmerigsmagie beschäftiged sind meistens eifach Dieb."
Should probably be: "...meistens eifach Dieb**e**."

**Comment by Ironbell** [comment]
Ich würs glaub so sege. Also beides gaht glaub. Aber ich enderes mal :)
