### ISSUE TITLE
Strange dirt line

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#86]
Found these two little lines on the ground, is it a grafic bug?

![littlething](https://user-images.githubusercontent.com/12735077/32694719-4d87a4c0-c747-11e7-8b7a-2a4c3e5ac827.PNG)
![littlething2](https://user-images.githubusercontent.com/12735077/32694720-4eb9c440-c747-11e7-950b-aebda2d0c8ce.PNG)

**Comment by Ironbell** [comment]
It's actually some pixels on the tileset that shouldn't be there. I'll remove them.
