### ISSUE TITLE
Skill/Gem placement

### ISSUE THREAD

**Issue by OGwold** [tizian/Cendric2#88]
Hard to write, but I'll try. Picture below to follow along.
Skills/gems from the spell book has priority over the weapons spell slots and gem sockets, but the spells/gems already equipped on the weapon don't have priority.
If I would like to change the order of my spells and have Fire Bolt as my 2nd skill, I'd need to either drag it from my spell book, or delete the Ice Bolt and drag my equipped Fire Bolt down one notch. If I try to place the already equipped Fire Bolt onto the Ice Bolt, the Fire Bolt disappears. 
The same is for gems. If I'd like to change my Speed gem on my Fire Bolt to a Count gem, I'l have to go to the gem section in the spell book and place that gem, or remove the gem in place and drag the one from Ice Bolt up. If I only drag the one from my Ice Bolt on top, it disappears and I need to get it again from the spell book. 
![124r](https://user-images.githubusercontent.com/33553242/32694999-86d61eba-c750-11e7-96c7-0a29c62e1fe3.png)

**Comment by Ironbell** [comment]
I was just lazy and didn't implement that.
