### ISSUE TITLE
Skeleton hits through wall

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#94]
In the temple of Yasha, there's a skeleton hitting Cendric through a wall if he stands close enough (visible in the screenshot)

![skeleton_hitting_through_wall](https://user-images.githubusercontent.com/33552615/32703940-d15e34ba-c7fd-11e7-9f02-ba9f07a8691d.JPG)

**Comment by Ironbell** [comment]
Decided that I won't fix that. The skeleton can't see, it only feels where you are, so it tries to hit cendric anyway. I  want to keep it because there are enemies that will destroy blocks to get to you and this looks cool. You'll get the points for your observation nevertheless.
