### ISSUE TITLE
Lots of objects you should not be able to move through

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#95]
In the room after killing Yasha, there are a lot of objects Cendric can illogically move through (marked in screenshot).

![immaterial_objects_yasha](https://user-images.githubusercontent.com/33552615/32704184-69c58d90-c801-11e7-83a3-f088f007284e.JPG)

**Comment by Ironbell** [comment]
check #92 😄

**Comment by Kylaine** [comment]
woops

**Comment by Ironbell** [comment]
no problem. thank you anyway :)
