### ISSUE TITLE
should these plates be able to be frozen?

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#97]
see title + screenshot

![frozen](https://user-images.githubusercontent.com/33552615/32704536-1621ce6e-c807-11e7-8fd9-9a2ce1ff2425.JPG)

**Comment by Ironbell** [comment]
Yes, as long as there's water. But the water looks really ugly there tbh. Maybe we could reduce it to only fill the middle part or put those two blocks you pointed out 1 tile lower.

**Comment by Ironbell** [comment]
better? :)

![image](https://user-images.githubusercontent.com/9303244/32704624-8ccbb470-c808-11e7-9ae6-da3a052aee84.png)
