### ISSUE TITLE
Inina's note

### ISSUE THREAD

**Issue by Kylaine** [tizian/Cendric2#98]
The swiss german version says: "...Kristall z'fülle. Bitte!..."

Is there some sort of "Hilfe" missing? It feels weird to read.

![ininas_note](https://user-images.githubusercontent.com/33552615/32704811-d7b532b0-c80b-11e7-88ee-88cb443a94a9.JPG)

**Comment by Ironbell** [comment]
No, she's just very confused at this point and can't think straight...
